### ISSUE TITLE
Issue in Hello World Program

### ISSUE THREAD

**Issue by IamEhtesham-ul-Haq** [IamEhtesham-ul-Haq/cpp-practice#2]
I am facing an unexpected error in the Hello World Program . .https://github.com/IamEhtesham-ul-Haq/cpp-practice/commit/ca72ed6c798f9eee90a02517bf91fcf9bfd32e6a

**Comment by HammadMaqbool** [comment]
tried any solution?

**Comment by IamEhtesham-ul-Haq** [comment]
> tried any solution?

Not yet
